# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HR_RR_Monitoring.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(749, 540)
        self.centralwidget = QtWidgets.QWidget(UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.conn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.conn_btn.setStyleSheet("")
        self.conn_btn.setCheckable(True)
        self.conn_btn.setObjectName("conn_btn")
       
        self.verticalLayout.addWidget(self.conn_btn)
        self.modeSelection = QtWidgets.QHBoxLayout()
        self.modeSelection.setObjectName("modeSelection")
        
        self.modeSelect = QtWidgets.QComboBox(self.centralwidget)
        self.modeSelect.setObjectName("modeSelect")
        self.modeSelect.addItem("")
        self.modeSelect.addItem("")
        self.modeSelect.addItem("")
        self.modeSelection.addWidget(self.modeSelect)
        
        self.conn_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.conn_label.setFont(font)
        self.conn_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border: 1px solid black")
        self.conn_label.setScaledContents(False)
        self.conn_label.setAlignment(QtCore.Qt.AlignCenter)
        self.conn_label.setWordWrap(False)
        self.conn_label.setOpenExternalLinks(False)
        self.conn_label.setObjectName("conn_label")
        self.modeSelection.addWidget(self.conn_label)
        
        self.updateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.updateBtn.setCheckable(True)
        self.updateBtn.setObjectName("updateBtn")
        self.modeSelection.addWidget(self.updateBtn)
        self.verticalLayout.addLayout(self.modeSelection)
        
        # horizontal layout with save button and FS selection
        self.saveStatus = QtWidgets.QHBoxLayout()
        self.FSR_Select = QtWidgets.QComboBox(self.centralwidget)
        self.FSR_Select.setEditable(False)
        self.FSR_Select.setObjectName("FSR_Select")
        self.FSR_Select.addItem("FS: ±2 g")
        self.FSR_Select.addItem("FS: ±4 g")
        self.FSR_Select.addItem("FS: ±8 g")
        self.FSR_Select.addItem("FS: ±16 g")
        self.saveStatus.addWidget(self.FSR_Select)

        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setObjectName("save_btn")
        self.saveStatus.addWidget(self.save_btn) 
        self.verticalLayout.addLayout(self.saveStatus)

        self.acc_plot = PlotWidget(self.centralwidget)
        self.acc_plot.setMinimumSize(QtCore.QSize(50, 30))
        #self.acc_plot.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.acc_plot.setLineWidth(2)
        self.acc_plot.setObjectName("acc_plot")
        self.acc_plot.showGrid(x=True, y=True)
        self.acc_plot.setBackground("w")
        self.acc_plot.setTitle("Acceleration data")
        styles = {'color':'k', 'font-size':'15px'}
        self.acc_plot.setLabel('left','Acceleartion [g]', **styles)
        self.acc_plot.setLabel('bottom','Time [s]', **styles)
        self.verticalLayout.addWidget(self.acc_plot)
        
        self.acc_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.acc_label.setFont(font)
        self.acc_label.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"border: 1px solid black")
        self.acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_label.setObjectName("acc_label")
        self.verticalLayout.addWidget(self.acc_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.RR_plot = PlotWidget(self.centralwidget)
        #self.RR_plot.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.RR_plot.setObjectName("RR_plot")
        self.RR_plot.showGrid(x=True, y=True)
        self.RR_plot.setBackground("w")
        self.RR_plot.setTitle("Respiratory data")
        self.RR_plot.setLabel('left','Acceleration [g]', **styles)
        self.RR_plot.setLabel('bottom','Time [s]', **styles)
        self.gridLayout.addWidget(self.RR_plot, 0, 0, 1, 1)

        self.HR_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.HR_label.setFont(font)
        self.HR_label.setStyleSheet("border: 1px solid black")
        self.HR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.HR_label.setObjectName("HR_label")
        self.gridLayout.addWidget(self.HR_label, 1, 1, 1, 1)
        self.RR_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.RR_label.setFont(font)
        self.RR_label.setStyleSheet("border: 1px solid black")
        self.RR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.RR_label.setOpenExternalLinks(False)
        self.RR_label.setObjectName("RR_label")
        self.gridLayout.addWidget(self.RR_label, 1, 0, 1, 1)
        
        self.HR_plot = PlotWidget(self.centralwidget)
        #self.HR_plot.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.HR_plot.setObjectName("HR_plot")
        self.HR_plot.showGrid(x=True, y=True)
        self.HR_plot.setBackground("w")
        self.HR_plot.setTitle("Respiratory data")
        self.HR_plot.setLabel('left','Acceleration [g]', **styles)
        self.HR_plot.setLabel('bottom','Time [s]', **styles)
        self.gridLayout.addWidget(self.RR_plot, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.HR_plot, 0, 1, 1, 1)

        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        UserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserWindow)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "HR_RR_Monitoring"))
        self.conn_btn.setText(_translate("UserWindow", "Device Search"))
        self.modeSelect.setItemText(0, _translate("UserWindow", "HR Only"))
        self.modeSelect.setItemText(1, _translate("UserWindow", "RR Only"))
        self.modeSelect.setItemText(2, _translate("UserWindow", "Both"))
        self.conn_label.setText(_translate("UserWindow", "NO DEVICE IS CONNECTED"))
        self.updateBtn.setText(_translate("UserWindow", "Start"))
        self.save_btn.setText(_translate("UserWindow", "SAVE STATUS"))
        self.acc_label.setText(_translate("UserWindow", "Accelerometer data"))
        self.HR_label.setText(_translate("UserWindow", "Instant HR value:"))
        self.RR_label.setText(_translate("UserWindow", "Instant RR value:"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserWindow = QtWidgets.QMainWindow()
    ui = Ui_UserWindow()
    ui.setupUi(UserWindow)
    UserWindow.show()
    sys.exit(app.exec_())
